development:
  base_url: http://esperto_fit_academy_web_1:4000
  payment_url: http://esperto_fit_payments_web_1:6000
production:
  base_url: https://example.com.br
test:
  base_url: http://esperto_fit_academy_web_1:4000
  payment_url: http://esperto_fit_payments_web_1:6000